[default]
extend-ignore-re = [
    # Hex literals (including digit separators and integer suffixes) can
    # false-positive as words.
    "(?i)0x[A-F0-9']+(UL{0,2})?",
    # Ignore blocks between `# spellchecker:off` and `# spellchecker:on`
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]
